CREATE TABLE IF NOT EXISTS scores (id INTEGER PRIMARY KEY AUTOINCREMENT, board TEXT NOT NULL, handle TEXT NOT NULL, score INTEGER NOT NULL, bestcut INTEGER NOT NULL DEFAULT 0, razors INTEGER NOT NULL DEFAULT 0, lvl INTEGER NOT NULL DEFAULT 0, ts INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_scores_board_score ON scores (board, score DESC);
